kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kebabcase-release-name" . }}-cloud-sql-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: cloud-sql-proxy
    app.kubernetes.io/component: rbac
    app: burp-suite-enterprise
{{ include "recommended-labels" . | indent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: burp-cloud-sql-proxy@{{ .Values.custom.gcpProject }}.iam.gserviceaccount.com
